# Generated by Django 4.0.4 on 2022-11-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.CharField(max_length=250)),
                ('supplierID', models.CharField(max_length=100)),
            ],
        ),
    ]
