# Generated by Django 4.0.4 on 2022-11-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_item_cost_alter_item_sellingprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
