# Generated by Django 4.1.3 on 2022-12-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_customer_shipment_supplier_order_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
